/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type CtaButton = {
  _type: "ctaButton";
  text?: string;
  variant?: "filled" | "outline";
  alignment?: "inherit" | "left" | "center" | "right";
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  openInNewTab?: boolean;
  externalUrl?: string;
};

export type TextImage = {
  _type: "textImage";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "body-3xl" | "body-2xl" | "body-xl" | "body-lg" | "body-sm" | "body-xs" | "standout";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    } | {
      _key: string;
    } & Color>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  layout?: "text-left" | "text-right";
};

export type Quote = {
  _type: "quote";
  text?: string;
  attribution?: string;
  textAlign?: "inherit" | "left" | "center" | "right";
};

export type BandcampWidget = {
  _type: "bandcampWidget";
  embedCode?: string;
};

export type SpotifyWidget = {
  _type: "spotifyWidget";
  url?: string;
  height?: "compact" | "normal";
};

export type YouTubeVideo = {
  _type: "youTubeVideo";
  url?: string;
};

export type ImageGallery = {
  _type: "imageGallery";
  columns?: "2" | "3" | "4";
  images?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    caption?: string;
    _key: string;
  }>;
};

export type ImageBlock = {
  _type: "imageBlock";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  size?: "full" | "small";
  caption?: string;
};

export type CardGrid = {
  _type: "cardGrid";
  columns?: "2" | "3" | "4";
  cards?: Array<{
    _key: string;
  } & CtaCard>;
};

export type CtaCard = {
  _type: "ctaCard";
  icon?: Icon;
  title?: string;
  bodyText?: string;
  button?: EmbeddedCtaButton;
};

export type Icon = {
  _type: "icon";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  alignment?: "left" | "center" | "right";
};

export type RichText = {
  _type: "richText";
  isCallout?: boolean;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "body-3xl" | "body-2xl" | "body-xl" | "body-lg" | "body-sm" | "body-xs" | "standout";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    } | {
      _key: string;
    } & Color>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  textAlign?: "inherit" | "left" | "center" | "right";
};

export type ItemList = {
  _type: "itemList";
  alignment?: "left" | "center" | "right";
  items?: Array<{
    text?: string;
    icon?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _type: "listItem";
    _key: string;
  }>;
};

export type Divider = {
  _type: "divider";
  style?: "default";
};

export type SubSubSection = {
  _type: "subSubSection";
  title?: string;
  textAlign?: "inherit" | "left" | "center" | "right";
  content?: Array<{
    _key: string;
  } & Divider | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & RichText | {
    _key: string;
  } & Quote | {
    _key: string;
  } & TextImage | {
    _key: string;
  } & CtaCard | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CardGrid | {
    _key: string;
  } & Icon | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget>;
};

export type SubSection = {
  _type: "subSection";
  title?: string;
  textAlign?: "inherit" | "left" | "center" | "right";
  content?: Array<{
    _key: string;
  } & SubSubSection | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & RichText | {
    _key: string;
  } & Quote | {
    _key: string;
  } & TextImage | {
    _key: string;
  } & CtaCard | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CardGrid | {
    _key: string;
  } & Icon | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget>;
};

export type PageSection = {
  _type: "pageSection";
  title?: string;
  subtitle?: string;
  textAlign?: "inherit" | "left" | "center" | "right";
  content?: Array<{
    _key: string;
  } & SubSection | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & RichText | {
    _key: string;
  } & Quote | {
    _key: string;
  } & TextImage | {
    _key: string;
  } & CtaCard | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CardGrid | {
    _key: string;
  } & Icon | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget>;
};

export type Section = {
  _type: "section";
  title?: string;
  textAlign?: "inherit" | "left" | "center" | "right";
  content?: Array<{
    _key: string;
  } & Section | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & RichText | {
    _key: string;
  } & Quote | {
    _key: string;
  } & TextImage | {
    _key: string;
  } & CtaCard | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CardGrid | {
    _key: string;
  } & Icon | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget>;
};

export type PageBuilder = Array<{
  _key: string;
} & PageSection | {
  _key: string;
} & Divider | {
  _key: string;
} & ItemList | {
  _key: string;
} & RichText | {
  _key: string;
} & Quote | {
  _key: string;
} & TextImage | {
  _key: string;
} & CtaCard | {
  _key: string;
} & CtaButton | {
  _key: string;
} & CardGrid | {
  _key: string;
} & Icon | {
  _key: string;
} & ImageBlock | {
  _key: string;
} & ImageGallery | {
  _key: string;
} & YouTubeVideo | {
  _key: string;
} & SpotifyWidget | {
  _key: string;
} & BandcampWidget>;

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyInfo?: {
    companyName?: string;
    description?: string;
    logo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  contactInfo?: {
    email?: string;
    phone?: string;
    address?: string;
  };
  footerColumns?: Array<{
    columnTitle?: string;
    links?: Array<{
      label?: string;
      url?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  socialMedia?: Array<{
    platform?: "facebook" | "twitter" | "instagram" | "linkedin" | "youtube" | "tiktok" | "other";
    url?: string;
    customName?: string;
    _key: string;
  }>;
  copyrightText?: string;
  bottomLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
};

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "body-3xl" | "body-2xl" | "body-xl" | "body-lg" | "body-sm" | "body-xs" | "standout";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  } | {
    _key: string;
  } & Color>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  publishedAt?: string;
  body?: BlockContent;
  relatedPosts?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "post";
  }>;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: PageBuilder;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroTitle?: string;
  heroSubtitle?: string;
  enableHeroCallToAction?: boolean;
  heroCallToAction?: EmbeddedCtaButton;
  heroContentPosition?: "top-left" | "top-center" | "top-right" | "center-left" | "center-center" | "center-right" | "bottom-left" | "bottom-center" | "bottom-right";
  content?: PageBuilder;
};

export type EmbeddedCtaButton = {
  _type: "embeddedCtaButton";
  text?: string;
  variant?: "filled" | "outline";
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  openInNewTab?: boolean;
  externalUrl?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  companyEmail?: string;
  siteDescription?: string;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = CtaButton | TextImage | Quote | BandcampWidget | SpotifyWidget | YouTubeVideo | ImageGallery | ImageBlock | CardGrid | CtaCard | Icon | RichText | ItemList | Divider | SubSubSection | SubSection | PageSection | Section | PageBuilder | Footer | Header | BlockContent | Post | Page | HomePage | EmbeddedCtaButton | SiteSettings | Color | RgbaColor | HsvaColor | HslaColor | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]|order(publishedAt desc)[0...12]{  _id,  title,  slug,  body,  mainImage{    asset,    alt  },  publishedAt}
export type POSTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  body: BlockContent | null;
  mainImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    alt: string | null;
  } | null;
  publishedAt: string | null;
}>;
// Variable: POSTS_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{   "slug": slug.current}
export type POSTS_SLUGS_QUERYResult = Array<{
  slug: string | null;
}>;
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{  _id,  title,  body,  mainImage{    asset,    alt  },  publishedAt,  relatedPosts[]->{    _id,    title,    slug,    mainImage{      asset,      alt    },    publishedAt  }}
export type POST_QUERYResult = {
  _id: string;
  title: string | null;
  body: BlockContent | null;
  mainImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    alt: string | null;
  } | null;
  publishedAt: string | null;
  relatedPosts: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    mainImage: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
    } | null;
    publishedAt: string | null;
  }> | null;
} | null;
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{  _id,  _type,  title,  slug,  content[]{    ...,    image{      asset,      alt,      hotspot,      crop    },    _type == "ctaButton" => {      ...,      internalLink->{        _id,        title,        slug      }    },    content[]{      ...,      image{        asset,        alt,        hotspot,        crop      },      _type == "ctaButton" => {        ...,        internalLink->{          _id,          title,          slug        }      },      content[]{        ...,        image{          asset,          alt,          hotspot,          crop        },        _type == "ctaButton" => {          ...,          internalLink->{            _id,            title,            slug          }        }      }    }  },  mainImage{    asset,    alt  }}
export type PAGE_QUERYResult = {
  _id: string;
  _type: "page";
  title: string | null;
  slug: Slug | null;
  content: Array<{
    _key: string;
    _type: "bandcampWidget";
    embedCode?: string;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "cardGrid";
    columns?: "2" | "3" | "4";
    cards?: Array<{
      _key: string;
    } & CtaCard>;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "ctaButton";
    text?: string;
    variant?: "filled" | "outline";
    alignment?: "center" | "inherit" | "left" | "right";
    linkType?: "external" | "internal";
    internalLink: {
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | null;
    openInNewTab?: boolean;
    externalUrl?: string;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "ctaCard";
    icon?: Icon;
    title?: string;
    bodyText?: string;
    button?: EmbeddedCtaButton;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "divider";
    style?: "default";
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "icon";
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    alignment?: "center" | "left" | "right";
    content: null;
  } | {
    _key: string;
    _type: "imageBlock";
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    size?: "full" | "small";
    caption?: string;
    content: null;
  } | {
    _key: string;
    _type: "imageGallery";
    columns?: "2" | "3" | "4";
    images?: Array<{
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      caption?: string;
      _key: string;
    }>;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "itemList";
    alignment?: "center" | "left" | "right";
    items?: Array<{
      text?: string;
      icon?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      _type: "listItem";
      _key: string;
    }>;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "pageSection";
    title?: string;
    subtitle?: string;
    textAlign?: "center" | "inherit" | "left" | "right";
    content: Array<{
      _key: string;
      _type: "bandcampWidget";
      embedCode?: string;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "cardGrid";
      columns?: "2" | "3" | "4";
      cards?: Array<{
        _key: string;
      } & CtaCard>;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "ctaButton";
      text?: string;
      variant?: "filled" | "outline";
      alignment?: "center" | "inherit" | "left" | "right";
      linkType?: "external" | "internal";
      internalLink: {
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | null;
      openInNewTab?: boolean;
      externalUrl?: string;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "ctaCard";
      icon?: Icon;
      title?: string;
      bodyText?: string;
      button?: EmbeddedCtaButton;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "divider";
      style?: "default";
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "icon";
      image: {
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      alignment?: "center" | "left" | "right";
      content: null;
    } | {
      _key: string;
      _type: "imageBlock";
      image: {
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      size?: "full" | "small";
      caption?: string;
      content: null;
    } | {
      _key: string;
      _type: "imageGallery";
      columns?: "2" | "3" | "4";
      images?: Array<{
        image?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        caption?: string;
        _key: string;
      }>;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "itemList";
      alignment?: "center" | "left" | "right";
      items?: Array<{
        text?: string;
        icon?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        _type: "listItem";
        _key: string;
      }>;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "quote";
      text?: string;
      attribution?: string;
      textAlign?: "center" | "inherit" | "left" | "right";
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "richText";
      isCallout?: boolean;
      content: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
        listItem?: "bullet";
        markDefs?: Array<{
          _key: string;
        } & Color | {
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
        image: null;
      } | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
        image: null;
      }> | null;
      textAlign?: "center" | "inherit" | "left" | "right";
      image: null;
    } | {
      _key: string;
      _type: "spotifyWidget";
      url?: string;
      height?: "compact" | "normal";
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "subSection";
      title?: string;
      textAlign?: "center" | "inherit" | "left" | "right";
      content: Array<{
        _key: string;
        _type: "bandcampWidget";
        embedCode?: string;
        image: null;
      } | {
        _key: string;
        _type: "cardGrid";
        columns?: "2" | "3" | "4";
        cards?: Array<{
          _key: string;
        } & CtaCard>;
        image: null;
      } | {
        _key: string;
        _type: "ctaButton";
        text?: string;
        variant?: "filled" | "outline";
        alignment?: "center" | "inherit" | "left" | "right";
        linkType?: "external" | "internal";
        internalLink: {
          _id: string;
          title: string | null;
          slug: Slug | null;
        } | null;
        openInNewTab?: boolean;
        externalUrl?: string;
        image: null;
      } | {
        _key: string;
        _type: "ctaCard";
        icon?: Icon;
        title?: string;
        bodyText?: string;
        button?: EmbeddedCtaButton;
        image: null;
      } | {
        _key: string;
        _type: "divider";
        style?: "default";
        image: null;
      } | {
        _key: string;
        _type: "icon";
        image: {
          asset: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        alignment?: "center" | "left" | "right";
      } | {
        _key: string;
        _type: "imageBlock";
        image: {
          asset: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        size?: "full" | "small";
        caption?: string;
      } | {
        _key: string;
        _type: "imageGallery";
        columns?: "2" | "3" | "4";
        images?: Array<{
          image?: {
            asset?: {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: "image";
          };
          caption?: string;
          _key: string;
        }>;
        image: null;
      } | {
        _key: string;
        _type: "itemList";
        alignment?: "center" | "left" | "right";
        items?: Array<{
          text?: string;
          icon?: {
            asset?: {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: "image";
          };
          _type: "listItem";
          _key: string;
        }>;
        image: null;
      } | {
        _key: string;
        _type: "quote";
        text?: string;
        attribution?: string;
        textAlign?: "center" | "inherit" | "left" | "right";
        image: null;
      } | {
        _key: string;
        _type: "richText";
        isCallout?: boolean;
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
          listItem?: "bullet";
          markDefs?: Array<{
            _key: string;
          } & Color | {
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        } | {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }>;
        textAlign?: "center" | "inherit" | "left" | "right";
        image: null;
      } | {
        _key: string;
        _type: "spotifyWidget";
        url?: string;
        height?: "compact" | "normal";
        image: null;
      } | {
        _key: string;
        _type: "subSubSection";
        title?: string;
        textAlign?: "center" | "inherit" | "left" | "right";
        content?: Array<{
          _key: string;
        } & BandcampWidget | {
          _key: string;
        } & CardGrid | {
          _key: string;
        } & CtaButton | {
          _key: string;
        } & CtaCard | {
          _key: string;
        } & Divider | {
          _key: string;
        } & Icon | {
          _key: string;
        } & ImageBlock | {
          _key: string;
        } & ImageGallery | {
          _key: string;
        } & ItemList | {
          _key: string;
        } & Quote | {
          _key: string;
        } & RichText | {
          _key: string;
        } & SpotifyWidget | {
          _key: string;
        } & TextImage | {
          _key: string;
        } & YouTubeVideo>;
        image: null;
      } | {
        _key: string;
        _type: "textImage";
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
          listItem?: "bullet";
          markDefs?: Array<{
            _key: string;
          } & Color | {
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        } | {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }>;
        image: {
          asset: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        layout?: "text-left" | "text-right";
      } | {
        _key: string;
        _type: "youTubeVideo";
        url?: string;
        image: null;
      }> | null;
      image: null;
    } | {
      _key: string;
      _type: "textImage";
      content: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
        listItem?: "bullet";
        markDefs?: Array<{
          _key: string;
        } & Color | {
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
        image: null;
      } | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
        image: null;
      }> | null;
      image: {
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      layout?: "text-left" | "text-right";
    } | {
      _key: string;
      _type: "youTubeVideo";
      url?: string;
      image: null;
      content: null;
    }> | null;
    image: null;
  } | {
    _key: string;
    _type: "quote";
    text?: string;
    attribution?: string;
    textAlign?: "center" | "inherit" | "left" | "right";
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "richText";
    isCallout?: boolean;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
      listItem?: "bullet";
      markDefs?: Array<{
        _key: string;
      } & Color | {
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
      image: null;
      content: null;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
      image: null;
      content: null;
    }> | null;
    textAlign?: "center" | "inherit" | "left" | "right";
    image: null;
  } | {
    _key: string;
    _type: "spotifyWidget";
    url?: string;
    height?: "compact" | "normal";
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "textImage";
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
      listItem?: "bullet";
      markDefs?: Array<{
        _key: string;
      } & Color | {
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
      image: null;
      content: null;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
      image: null;
      content: null;
    }> | null;
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    layout?: "text-left" | "text-right";
  } | {
    _key: string;
    _type: "youTubeVideo";
    url?: string;
    image: null;
    content: null;
  }> | null;
  mainImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    alt: null;
  } | null;
} | null;
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{  _id,  _type,  heroImage{    asset,    alt  },  heroTitle,  heroSubtitle,  enableHeroCallToAction,  heroCallToAction{    text,    linkType,    internalLink->{      _id,      title,      slug    },    externalLink,    openInNewTab  },  heroContentPosition,  content[]{    ...,    image{      asset,      alt,      hotspot,      crop    },    _type == "ctaButton" => {      ...,      internalLink->{        _id,        title,        slug      }    },    content[]{      ...,      image{        asset,        alt,        hotspot,        crop      },      _type == "ctaButton" => {        ...,        internalLink->{          _id,          title,          slug        }      },      content[]{        ...,        image{          asset,          alt,          hotspot,          crop        },        _type == "ctaButton" => {          ...,          internalLink->{            _id,            title,            slug          }        }      }    }  }}
export type HOME_PAGE_QUERYResult = {
  _id: string;
  _type: "footer";
  heroImage: null;
  heroTitle: null;
  heroSubtitle: null;
  enableHeroCallToAction: null;
  heroCallToAction: null;
  heroContentPosition: null;
  content: null;
} | {
  _id: string;
  _type: "header";
  heroImage: null;
  heroTitle: null;
  heroSubtitle: null;
  enableHeroCallToAction: null;
  heroCallToAction: null;
  heroContentPosition: null;
  content: null;
} | {
  _id: string;
  _type: "homePage";
  heroImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    alt: string | null;
  } | null;
  heroTitle: string | null;
  heroSubtitle: string | null;
  enableHeroCallToAction: boolean | null;
  heroCallToAction: {
    text: string | null;
    linkType: "external" | "internal" | null;
    internalLink: {
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | null;
    externalLink: null;
    openInNewTab: boolean | null;
  } | null;
  heroContentPosition: "bottom-center" | "bottom-left" | "bottom-right" | "center-center" | "center-left" | "center-right" | "top-center" | "top-left" | "top-right" | null;
  content: Array<{
    _key: string;
    _type: "bandcampWidget";
    embedCode?: string;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "cardGrid";
    columns?: "2" | "3" | "4";
    cards?: Array<{
      _key: string;
    } & CtaCard>;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "ctaButton";
    text?: string;
    variant?: "filled" | "outline";
    alignment?: "center" | "inherit" | "left" | "right";
    linkType?: "external" | "internal";
    internalLink: {
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | null;
    openInNewTab?: boolean;
    externalUrl?: string;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "ctaCard";
    icon?: Icon;
    title?: string;
    bodyText?: string;
    button?: EmbeddedCtaButton;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "divider";
    style?: "default";
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "icon";
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    alignment?: "center" | "left" | "right";
    content: null;
  } | {
    _key: string;
    _type: "imageBlock";
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    size?: "full" | "small";
    caption?: string;
    content: null;
  } | {
    _key: string;
    _type: "imageGallery";
    columns?: "2" | "3" | "4";
    images?: Array<{
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      caption?: string;
      _key: string;
    }>;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "itemList";
    alignment?: "center" | "left" | "right";
    items?: Array<{
      text?: string;
      icon?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      _type: "listItem";
      _key: string;
    }>;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "pageSection";
    title?: string;
    subtitle?: string;
    textAlign?: "center" | "inherit" | "left" | "right";
    content: Array<{
      _key: string;
      _type: "bandcampWidget";
      embedCode?: string;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "cardGrid";
      columns?: "2" | "3" | "4";
      cards?: Array<{
        _key: string;
      } & CtaCard>;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "ctaButton";
      text?: string;
      variant?: "filled" | "outline";
      alignment?: "center" | "inherit" | "left" | "right";
      linkType?: "external" | "internal";
      internalLink: {
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | null;
      openInNewTab?: boolean;
      externalUrl?: string;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "ctaCard";
      icon?: Icon;
      title?: string;
      bodyText?: string;
      button?: EmbeddedCtaButton;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "divider";
      style?: "default";
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "icon";
      image: {
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      alignment?: "center" | "left" | "right";
      content: null;
    } | {
      _key: string;
      _type: "imageBlock";
      image: {
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      size?: "full" | "small";
      caption?: string;
      content: null;
    } | {
      _key: string;
      _type: "imageGallery";
      columns?: "2" | "3" | "4";
      images?: Array<{
        image?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        caption?: string;
        _key: string;
      }>;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "itemList";
      alignment?: "center" | "left" | "right";
      items?: Array<{
        text?: string;
        icon?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        _type: "listItem";
        _key: string;
      }>;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "quote";
      text?: string;
      attribution?: string;
      textAlign?: "center" | "inherit" | "left" | "right";
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "richText";
      isCallout?: boolean;
      content: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
        listItem?: "bullet";
        markDefs?: Array<{
          _key: string;
        } & Color | {
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
        image: null;
      } | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
        image: null;
      }> | null;
      textAlign?: "center" | "inherit" | "left" | "right";
      image: null;
    } | {
      _key: string;
      _type: "spotifyWidget";
      url?: string;
      height?: "compact" | "normal";
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "subSection";
      title?: string;
      textAlign?: "center" | "inherit" | "left" | "right";
      content: Array<{
        _key: string;
        _type: "bandcampWidget";
        embedCode?: string;
        image: null;
      } | {
        _key: string;
        _type: "cardGrid";
        columns?: "2" | "3" | "4";
        cards?: Array<{
          _key: string;
        } & CtaCard>;
        image: null;
      } | {
        _key: string;
        _type: "ctaButton";
        text?: string;
        variant?: "filled" | "outline";
        alignment?: "center" | "inherit" | "left" | "right";
        linkType?: "external" | "internal";
        internalLink: {
          _id: string;
          title: string | null;
          slug: Slug | null;
        } | null;
        openInNewTab?: boolean;
        externalUrl?: string;
        image: null;
      } | {
        _key: string;
        _type: "ctaCard";
        icon?: Icon;
        title?: string;
        bodyText?: string;
        button?: EmbeddedCtaButton;
        image: null;
      } | {
        _key: string;
        _type: "divider";
        style?: "default";
        image: null;
      } | {
        _key: string;
        _type: "icon";
        image: {
          asset: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        alignment?: "center" | "left" | "right";
      } | {
        _key: string;
        _type: "imageBlock";
        image: {
          asset: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        size?: "full" | "small";
        caption?: string;
      } | {
        _key: string;
        _type: "imageGallery";
        columns?: "2" | "3" | "4";
        images?: Array<{
          image?: {
            asset?: {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: "image";
          };
          caption?: string;
          _key: string;
        }>;
        image: null;
      } | {
        _key: string;
        _type: "itemList";
        alignment?: "center" | "left" | "right";
        items?: Array<{
          text?: string;
          icon?: {
            asset?: {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: "image";
          };
          _type: "listItem";
          _key: string;
        }>;
        image: null;
      } | {
        _key: string;
        _type: "quote";
        text?: string;
        attribution?: string;
        textAlign?: "center" | "inherit" | "left" | "right";
        image: null;
      } | {
        _key: string;
        _type: "richText";
        isCallout?: boolean;
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
          listItem?: "bullet";
          markDefs?: Array<{
            _key: string;
          } & Color | {
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        } | {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }>;
        textAlign?: "center" | "inherit" | "left" | "right";
        image: null;
      } | {
        _key: string;
        _type: "spotifyWidget";
        url?: string;
        height?: "compact" | "normal";
        image: null;
      } | {
        _key: string;
        _type: "subSubSection";
        title?: string;
        textAlign?: "center" | "inherit" | "left" | "right";
        content?: Array<{
          _key: string;
        } & BandcampWidget | {
          _key: string;
        } & CardGrid | {
          _key: string;
        } & CtaButton | {
          _key: string;
        } & CtaCard | {
          _key: string;
        } & Divider | {
          _key: string;
        } & Icon | {
          _key: string;
        } & ImageBlock | {
          _key: string;
        } & ImageGallery | {
          _key: string;
        } & ItemList | {
          _key: string;
        } & Quote | {
          _key: string;
        } & RichText | {
          _key: string;
        } & SpotifyWidget | {
          _key: string;
        } & TextImage | {
          _key: string;
        } & YouTubeVideo>;
        image: null;
      } | {
        _key: string;
        _type: "textImage";
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
          listItem?: "bullet";
          markDefs?: Array<{
            _key: string;
          } & Color | {
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        } | {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }>;
        image: {
          asset: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        layout?: "text-left" | "text-right";
      } | {
        _key: string;
        _type: "youTubeVideo";
        url?: string;
        image: null;
      }> | null;
      image: null;
    } | {
      _key: string;
      _type: "textImage";
      content: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
        listItem?: "bullet";
        markDefs?: Array<{
          _key: string;
        } & Color | {
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
        image: null;
      } | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
        image: null;
      }> | null;
      image: {
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      layout?: "text-left" | "text-right";
    } | {
      _key: string;
      _type: "youTubeVideo";
      url?: string;
      image: null;
      content: null;
    }> | null;
    image: null;
  } | {
    _key: string;
    _type: "quote";
    text?: string;
    attribution?: string;
    textAlign?: "center" | "inherit" | "left" | "right";
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "richText";
    isCallout?: boolean;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
      listItem?: "bullet";
      markDefs?: Array<{
        _key: string;
      } & Color | {
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
      image: null;
      content: null;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
      image: null;
      content: null;
    }> | null;
    textAlign?: "center" | "inherit" | "left" | "right";
    image: null;
  } | {
    _key: string;
    _type: "spotifyWidget";
    url?: string;
    height?: "compact" | "normal";
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "textImage";
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
      listItem?: "bullet";
      markDefs?: Array<{
        _key: string;
      } & Color | {
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
      image: null;
      content: null;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
      image: null;
      content: null;
    }> | null;
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    layout?: "text-left" | "text-right";
  } | {
    _key: string;
    _type: "youTubeVideo";
    url?: string;
    image: null;
    content: null;
  }> | null;
} | {
  _id: string;
  _type: "page";
  heroImage: null;
  heroTitle: null;
  heroSubtitle: null;
  enableHeroCallToAction: null;
  heroCallToAction: null;
  heroContentPosition: null;
  content: Array<{
    _key: string;
    _type: "bandcampWidget";
    embedCode?: string;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "cardGrid";
    columns?: "2" | "3" | "4";
    cards?: Array<{
      _key: string;
    } & CtaCard>;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "ctaButton";
    text?: string;
    variant?: "filled" | "outline";
    alignment?: "center" | "inherit" | "left" | "right";
    linkType?: "external" | "internal";
    internalLink: {
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | null;
    openInNewTab?: boolean;
    externalUrl?: string;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "ctaCard";
    icon?: Icon;
    title?: string;
    bodyText?: string;
    button?: EmbeddedCtaButton;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "divider";
    style?: "default";
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "icon";
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    alignment?: "center" | "left" | "right";
    content: null;
  } | {
    _key: string;
    _type: "imageBlock";
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    size?: "full" | "small";
    caption?: string;
    content: null;
  } | {
    _key: string;
    _type: "imageGallery";
    columns?: "2" | "3" | "4";
    images?: Array<{
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      caption?: string;
      _key: string;
    }>;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "itemList";
    alignment?: "center" | "left" | "right";
    items?: Array<{
      text?: string;
      icon?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      _type: "listItem";
      _key: string;
    }>;
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "pageSection";
    title?: string;
    subtitle?: string;
    textAlign?: "center" | "inherit" | "left" | "right";
    content: Array<{
      _key: string;
      _type: "bandcampWidget";
      embedCode?: string;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "cardGrid";
      columns?: "2" | "3" | "4";
      cards?: Array<{
        _key: string;
      } & CtaCard>;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "ctaButton";
      text?: string;
      variant?: "filled" | "outline";
      alignment?: "center" | "inherit" | "left" | "right";
      linkType?: "external" | "internal";
      internalLink: {
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | null;
      openInNewTab?: boolean;
      externalUrl?: string;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "ctaCard";
      icon?: Icon;
      title?: string;
      bodyText?: string;
      button?: EmbeddedCtaButton;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "divider";
      style?: "default";
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "icon";
      image: {
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      alignment?: "center" | "left" | "right";
      content: null;
    } | {
      _key: string;
      _type: "imageBlock";
      image: {
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      size?: "full" | "small";
      caption?: string;
      content: null;
    } | {
      _key: string;
      _type: "imageGallery";
      columns?: "2" | "3" | "4";
      images?: Array<{
        image?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        caption?: string;
        _key: string;
      }>;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "itemList";
      alignment?: "center" | "left" | "right";
      items?: Array<{
        text?: string;
        icon?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        _type: "listItem";
        _key: string;
      }>;
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "quote";
      text?: string;
      attribution?: string;
      textAlign?: "center" | "inherit" | "left" | "right";
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "richText";
      isCallout?: boolean;
      content: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
        listItem?: "bullet";
        markDefs?: Array<{
          _key: string;
        } & Color | {
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
        image: null;
      } | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
        image: null;
      }> | null;
      textAlign?: "center" | "inherit" | "left" | "right";
      image: null;
    } | {
      _key: string;
      _type: "spotifyWidget";
      url?: string;
      height?: "compact" | "normal";
      image: null;
      content: null;
    } | {
      _key: string;
      _type: "subSection";
      title?: string;
      textAlign?: "center" | "inherit" | "left" | "right";
      content: Array<{
        _key: string;
        _type: "bandcampWidget";
        embedCode?: string;
        image: null;
      } | {
        _key: string;
        _type: "cardGrid";
        columns?: "2" | "3" | "4";
        cards?: Array<{
          _key: string;
        } & CtaCard>;
        image: null;
      } | {
        _key: string;
        _type: "ctaButton";
        text?: string;
        variant?: "filled" | "outline";
        alignment?: "center" | "inherit" | "left" | "right";
        linkType?: "external" | "internal";
        internalLink: {
          _id: string;
          title: string | null;
          slug: Slug | null;
        } | null;
        openInNewTab?: boolean;
        externalUrl?: string;
        image: null;
      } | {
        _key: string;
        _type: "ctaCard";
        icon?: Icon;
        title?: string;
        bodyText?: string;
        button?: EmbeddedCtaButton;
        image: null;
      } | {
        _key: string;
        _type: "divider";
        style?: "default";
        image: null;
      } | {
        _key: string;
        _type: "icon";
        image: {
          asset: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        alignment?: "center" | "left" | "right";
      } | {
        _key: string;
        _type: "imageBlock";
        image: {
          asset: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        size?: "full" | "small";
        caption?: string;
      } | {
        _key: string;
        _type: "imageGallery";
        columns?: "2" | "3" | "4";
        images?: Array<{
          image?: {
            asset?: {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: "image";
          };
          caption?: string;
          _key: string;
        }>;
        image: null;
      } | {
        _key: string;
        _type: "itemList";
        alignment?: "center" | "left" | "right";
        items?: Array<{
          text?: string;
          icon?: {
            asset?: {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: "image";
          };
          _type: "listItem";
          _key: string;
        }>;
        image: null;
      } | {
        _key: string;
        _type: "quote";
        text?: string;
        attribution?: string;
        textAlign?: "center" | "inherit" | "left" | "right";
        image: null;
      } | {
        _key: string;
        _type: "richText";
        isCallout?: boolean;
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
          listItem?: "bullet";
          markDefs?: Array<{
            _key: string;
          } & Color | {
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        } | {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }>;
        textAlign?: "center" | "inherit" | "left" | "right";
        image: null;
      } | {
        _key: string;
        _type: "spotifyWidget";
        url?: string;
        height?: "compact" | "normal";
        image: null;
      } | {
        _key: string;
        _type: "subSubSection";
        title?: string;
        textAlign?: "center" | "inherit" | "left" | "right";
        content?: Array<{
          _key: string;
        } & BandcampWidget | {
          _key: string;
        } & CardGrid | {
          _key: string;
        } & CtaButton | {
          _key: string;
        } & CtaCard | {
          _key: string;
        } & Divider | {
          _key: string;
        } & Icon | {
          _key: string;
        } & ImageBlock | {
          _key: string;
        } & ImageGallery | {
          _key: string;
        } & ItemList | {
          _key: string;
        } & Quote | {
          _key: string;
        } & RichText | {
          _key: string;
        } & SpotifyWidget | {
          _key: string;
        } & TextImage | {
          _key: string;
        } & YouTubeVideo>;
        image: null;
      } | {
        _key: string;
        _type: "textImage";
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
          listItem?: "bullet";
          markDefs?: Array<{
            _key: string;
          } & Color | {
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        } | {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }>;
        image: {
          asset: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        layout?: "text-left" | "text-right";
      } | {
        _key: string;
        _type: "youTubeVideo";
        url?: string;
        image: null;
      }> | null;
      image: null;
    } | {
      _key: string;
      _type: "textImage";
      content: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
        listItem?: "bullet";
        markDefs?: Array<{
          _key: string;
        } & Color | {
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
        image: null;
      } | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
        image: null;
      }> | null;
      image: {
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      layout?: "text-left" | "text-right";
    } | {
      _key: string;
      _type: "youTubeVideo";
      url?: string;
      image: null;
      content: null;
    }> | null;
    image: null;
  } | {
    _key: string;
    _type: "quote";
    text?: string;
    attribution?: string;
    textAlign?: "center" | "inherit" | "left" | "right";
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "richText";
    isCallout?: boolean;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
      listItem?: "bullet";
      markDefs?: Array<{
        _key: string;
      } & Color | {
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
      image: null;
      content: null;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
      image: null;
      content: null;
    }> | null;
    textAlign?: "center" | "inherit" | "left" | "right";
    image: null;
  } | {
    _key: string;
    _type: "spotifyWidget";
    url?: string;
    height?: "compact" | "normal";
    image: null;
    content: null;
  } | {
    _key: string;
    _type: "textImage";
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "body-2xl" | "body-3xl" | "body-lg" | "body-sm" | "body-xl" | "body-xs" | "normal" | "standout";
      listItem?: "bullet";
      markDefs?: Array<{
        _key: string;
      } & Color | {
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
      image: null;
      content: null;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
      image: null;
      content: null;
    }> | null;
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    layout?: "text-left" | "text-right";
  } | {
    _key: string;
    _type: "youTubeVideo";
    url?: string;
    image: null;
    content: null;
  }> | null;
} | {
  _id: string;
  _type: "post";
  heroImage: null;
  heroTitle: null;
  heroSubtitle: null;
  enableHeroCallToAction: null;
  heroCallToAction: null;
  heroContentPosition: null;
  content: null;
} | {
  _id: string;
  _type: "sanity.fileAsset";
  heroImage: null;
  heroTitle: null;
  heroSubtitle: null;
  enableHeroCallToAction: null;
  heroCallToAction: null;
  heroContentPosition: null;
  content: null;
} | {
  _id: string;
  _type: "sanity.imageAsset";
  heroImage: null;
  heroTitle: null;
  heroSubtitle: null;
  enableHeroCallToAction: null;
  heroCallToAction: null;
  heroContentPosition: null;
  content: null;
} | {
  _id: string;
  _type: "siteSettings";
  heroImage: null;
  heroTitle: null;
  heroSubtitle: null;
  enableHeroCallToAction: null;
  heroCallToAction: null;
  heroContentPosition: null;
  content: null;
} | null;
// Variable: HEADER_QUERY
// Query: *[_id == "header"][0]{  _id,  _type,  logo{    asset,    alt  }}
export type HEADER_QUERYResult = {
  _id: string;
  _type: "footer";
  logo: null;
} | {
  _id: string;
  _type: "header";
  logo: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    alt: null;
  } | null;
} | {
  _id: string;
  _type: "homePage";
  logo: null;
} | {
  _id: string;
  _type: "page";
  logo: null;
} | {
  _id: string;
  _type: "post";
  logo: null;
} | {
  _id: string;
  _type: "sanity.fileAsset";
  logo: null;
} | {
  _id: string;
  _type: "sanity.imageAsset";
  logo: null;
} | {
  _id: string;
  _type: "siteSettings";
  logo: null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"post\" && defined(slug.current)]|order(publishedAt desc)[0...12]{\n  _id,\n  title,\n  slug,\n  body,\n  mainImage{\n    asset,\n    alt\n  },\n  publishedAt\n}": POSTS_QUERYResult;
    "*[_type == \"post\" && defined(slug.current)]{ \n  \"slug\": slug.current\n}": POSTS_SLUGS_QUERYResult;
    "*[_type == \"post\" && slug.current == $slug][0]{\n  _id,\n  title,\n  body,\n  mainImage{\n    asset,\n    alt\n  },\n  publishedAt,\n  relatedPosts[]->{\n    _id,\n    title,\n    slug,\n    mainImage{\n      asset,\n      alt\n    },\n    publishedAt\n  }\n}": POST_QUERYResult;
    "*[_type == \"page\" && slug.current == $slug][0]{\n  _id,\n  _type,\n  title,\n  slug,\n  content[]{\n    ...,\n    image{\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n    _type == \"ctaButton\" => {\n      ...,\n      internalLink->{\n        _id,\n        title,\n        slug\n      }\n    },\n    content[]{\n      ...,\n      image{\n        asset,\n        alt,\n        hotspot,\n        crop\n      },\n      _type == \"ctaButton\" => {\n        ...,\n        internalLink->{\n          _id,\n          title,\n          slug\n        }\n      },\n      content[]{\n        ...,\n        image{\n          asset,\n          alt,\n          hotspot,\n          crop\n        },\n        _type == \"ctaButton\" => {\n          ...,\n          internalLink->{\n            _id,\n            title,\n            slug\n          }\n        }\n      }\n    }\n  },\n  mainImage{\n    asset,\n    alt\n  }\n}": PAGE_QUERYResult;
    "*[_id == \"homePage\"][0]{\n  _id,\n  _type,\n  heroImage{\n    asset,\n    alt\n  },\n  heroTitle,\n  heroSubtitle,\n  enableHeroCallToAction,\n  heroCallToAction{\n    text,\n    linkType,\n    internalLink->{\n      _id,\n      title,\n      slug\n    },\n    externalLink,\n    openInNewTab\n  },\n  heroContentPosition,\n  content[]{\n    ...,\n    image{\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n    _type == \"ctaButton\" => {\n      ...,\n      internalLink->{\n        _id,\n        title,\n        slug\n      }\n    },\n    content[]{\n      ...,\n      image{\n        asset,\n        alt,\n        hotspot,\n        crop\n      },\n      _type == \"ctaButton\" => {\n        ...,\n        internalLink->{\n          _id,\n          title,\n          slug\n        }\n      },\n      content[]{\n        ...,\n        image{\n          asset,\n          alt,\n          hotspot,\n          crop\n        },\n        _type == \"ctaButton\" => {\n          ...,\n          internalLink->{\n            _id,\n            title,\n            slug\n          }\n        }\n      }\n    }\n  }\n}": HOME_PAGE_QUERYResult;
    "*[_id == \"header\"][0]{\n  _id,\n  _type,\n  logo{\n    asset,\n    alt\n  }\n}": HEADER_QUERYResult;
  }
}
